FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

FROM nginx:stable-trixie-perl
COPY --from=builder /app/dist /usr/share/nginx/html
# Add custom nginx.conf to support React Router history fallback
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80